import express from "express";
import cors from "cors";
import multer from "multer";
import { ObjectId } from "mongodb";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import { connectDB } from "./db.js";
import pdf from "pdf-parse";
import product from "./products.json" with { type: "json"}


dotenv.config();
const ai = new GoogleGenAI({});

const app = express();
const upload = multer();

async function parsePDF(buffer) {
  const data = await pdf(buffer);
  return { text: data.text };
}

app.use(cors());
app.use(express.json()); // parses application/json
app.use(express.urlencoded({ extended: true })); // parses x-www-form-urlencoded

async function getAIQuestions(resumeText) {
  const prompt = `Generate 10 interview questions and answers based on this resume in strict JSON format:
[
  { "id": 1, "question": "...", "answer": "..."},
  { "id": 2, "question": "...", "answer": "..."},
  ...
]:\n${resumeText}`;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });
    const rawText = response.text || ""; // 🚀 Correctly access the generated text
    // console.log(rawText);
    if (!rawText) throw new Error("No content generated by Gemini.");

    const cleaned = rawText
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();

    const questionsObj = JSON.parse(cleaned);
    return questionsObj;
  } catch (error) {
    console.error("❌ Error generating content with Gemini:", error);
    throw new Error("Failed to generate questions.");
  }
}

app.post("/upload", upload.single("resume"), async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ error: "No file uploaded" });
    if (req.file.mimetype !== "application/pdf")
      return res.status(400).json({ error: "Only PDF resumes supported" });

    const dataBuffer = req.file.buffer; // use buffer instead of fs

    const pdfData = await parsePDF(dataBuffer);
    const resumeText = pdfData.text;

    // STORE IN MONGODB (binary + text)
    const db = await connectDB();
    const resumes = db.collection("resumes");

    const result = await resumes.insertOne({
      filename: req.file.originalname,
      mimetype: req.file.mimetype,
      data: req.file.buffer,
      extractedText: resumeText,
      uploadedAt: new Date(),
    });
    const questions = await getAIQuestions(resumeText);

    return res.json({resumeId:result.insertedId ,questions});

  } catch (err) {
    console.error("❌ Error in /upload:", err);
    return res.status(500).json({ error: err.message });
  }
});



app.get("/download/:id", async (req, res) => {
  try {
    const db = await connectDB();
    const resumes = db.collection("resumes");

    const file = await resumes.findOne({ _id: new ObjectId(req.params.id) });

    if (!file) {
      return res.status(404).json({ error: "File not found" });
    }

    // Render inline instead of forcing download
    res.set({
      "Content-Type": file.mimetype,
      "Content-Disposition": `attachment; filename="${file.filename}"`,
    });

    return res.send(file.data.buffer);

  } catch (err) {
    console.error("❌ Error viewing file:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
});
app.get("/product", (req,res) => {
  res.json(product);
})

app.get("/", (req, res) => {
  res.send("Server is running ✅");
});
app.post("/get_answer", express.json(), async (req, res) => {
  try {
    const { question, answer } = req.body;
    if (!question) {
      return res.status(400).json({ error: "Question is required" });
    }

            const prompt = `
    You are a senior Frontend/React interview mentor.
    Your task is to help me prepare for frontend and React interviews.

    Given:
    Question: "${question}"
    Candidate Answer: "${answer}"

    Produce the following output in clean Markdown:

    ### Explanation
     Provide supporting answer and explain the concept in simple, accurate interview-focused terms.`;
    
    // const prompt = `You are a helpful front-end/software developer assistant. Provide a concise and relevant answer to the interview question below.
    // Keep the response focused and avoid unnecessary details.\nQuestion: ${question}`;
    
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-lite",
      contents: prompt,
    });
    const ai_answer = response.text || "No answer generated.";
    res.json({ answer: ai_answer.trim() });
  } catch (err) {
    console.error("❌ Error in /get_answer:", err);
    res.status(500).json({ error: err.message });
  }
});

const PORT = process.env.PORT || 5000;
// connectDB().catch(err => {
//   console.error("❌ MongoDB connection failed:", err);
//   process.exit(1);
// });

// app.listen(PORT, "0.0.0.0", () => {
//   console.log(`Server running on port ${PORT}`);
// });
export default app;